export const content = {
  ar: {
    nav: {
      logo: 'قوم',
      items: [
        { label: 'ابنِ صندوقك', href: '/build' },
        { label: 'طلب مسبق', href: '/preorder' },
        { label: 'كيف يعمل', href: '/how-it-works' },
        { label: 'هذا الموسم', href: '/season' },
        { label: 'عن قوم', href: '/about' },
      ],
      langSwitch: 'EN',
      cta: 'ابنِ صندوقك',
    },
    hero: {
      eyebrow: 'تصدير · مصنع · مصر',
      headline: 'جودة التصدير.\nسعر المصنع.',
      sub: 'أفضل مصانع مصر تلبّس العالم.\nالآن دورك.',
      learnMore: 'اكتشف أكثر',
    },
    grid: {
      label1: 'الكتان المصري — موسم ٢٠٢٥',
      label2: 'تشكيلة الرجال',
      label3: 'الأساسيات',
      label4: 'تشكيلة الكتان',
      label5: 'الإطلالات المميزة',
    },
    boxes: {
      eyebrow: 'هذا الموسم',
      title: 'صناديق مُصمَّمة بعناية',
      sub: 'كل قطعة مختارة يدوياً من مصانع التصدير المصرية المعتمدة',
      capsule: {
        tag: 'فردي',
        name: 'صندوق الكبسول',
        pieces: '٥ قطع مختارة يدوياً',
        desc: 'عُدّة أساسية مثالية للموسم — ٥ قطع متناسقة من أفضل مصانع مصر، تصل إلى بابك مباشرة.',
      },
      group: {
        tag: 'للمجموعة',
        name: 'صندوق المجموعة',
        pieces: '١٠ قطع مشتركة',
        desc: 'شارك الرابط مع أصدقائك وعائلتك، احجزوا معاً — كلما اكتمل الصندوق وفّرتم أكثر.',
      },
    },
    how: {
      title: 'كيف يعمل',
      steps: [
        { n: '٠١', title: 'اختر صندوقك', desc: 'كبسول فردي ٥ قطع لنفسك، أو صندوق مجموعة ١٠ قطع تبنيه مع أصدقائك وعائلتك.' },
        { n: '٠٢', title: 'اختر قطعك', desc: 'تصفّح المجموعة وأضف ما يناسبك — بسعر المصنع مباشرة، بدون وسيط.' },
        { n: '٠٣', title: 'شارك ووفّر', desc: 'شارك رابطك مع الأصدقاء. كلما اكتمل صندوق المجموعة، زاد الخصم للجميع.' },
      ],
    },
    sustain: {
      eyebrow: 'لماذا قوم',
      title: 'أكثر من مجرد ملابس',
      pillars: [
        { icon: '◎', title: 'صفر هدر', desc: 'نُحوّل فائض التصدير إلى فرصة حقيقية — لا إلى مكبّ نفايات' },
        { icon: '◈', title: 'صُنع في مصر', desc: 'نفس المصانع التي تلبّس العلامات العالمية — الآن لك، مباشرةً' },
        { icon: '◉', title: 'معاً نوفّر', desc: 'نموذج الصندوق الجماعي يجعل جودة التصدير في متناول الجميع' },
      ],
    },
    footer: {
      desc: 'ملابس بجودة التصدير، مباشرة من المصانع المصرية إلى بابك.',
      col1title: 'قوم',
      col1: ['عن قوم', 'الشفافية', 'مصانعنا', 'المدونة'],
      col2title: 'مساعدة',
      col2: ['تواصل معنا', 'الشحن والتوصيل', 'الإرجاع', 'الأسئلة الشائعة'],
      tagline: 'مصنوع في مصر. مُصمَّم للعالم.',
      copy: '© ٢٠٢٥ قوم — جميع الحقوق محفوظة',
    },
    builder: {
      step1: {
        eyebrow: 'ابدأ هنا',
        title: 'اختر نوع صندوقك',
        sub: 'صندوق الكبسول للتجربة الفردية، أو صندوق المجموعة لتوفر أكثر مع أصدقائك وعائلتك.',
        selectLabel: 'اختر هذا الصندوق',
        capsule: { tag: 'فردي', name: 'صندوق الكبسول', pieces: '٥ قطع', desc: 'عُدّة أساسية مثالية للموسم. ٥ قطع مختارة يدوياً من أفضل مصانع التصدير المصرية.', perks: ['٥ قطع', 'تسليم فوري', 'إرجاع مجاني'] },
        group: { tag: 'للمجموعة', name: 'صندوق المجموعة', discount: 'خصم إضافي', pieces: '١٠ قطع', desc: 'شارك الرابط مع أصدقائك — كلما اكتمل الصندوق زاد الخصم لكل الأعضاء.', perks: ['١٠ قطع', 'رابط مشاركة', 'خصم جماعي'] },
      },
      step2: {
        eyebrow: 'اختر قطعك',
        tabs: { all: 'الكل', tops: 'قمصان وبلوزات', trousers: 'بناطلون', dresses: 'فساتين وتنانير', outerwear: 'جاكيت' },
        selectedLabel: 'تم اختياره',
        back: 'رجوع',
        reviewBox: 'مراجعة الصندوق',
      },
      step3: {
        eyebrow: 'مراجعة الصندوق',
        title: 'صندوقك جاهز',
        emptySlot: 'فارغ',
        editBox: 'تعديل الاختيار',
        confirm: 'تأكيد الطلب',
        shareEyebrow: 'دعوة الأصدقاء',
        shareTitle: 'شارك وانتظر الخصم',
        shareDesc: 'شارك هذا الرابط مع أصدقائك. كلما انضم أكثر، زاد الخصم للجميع تلقائياً.',
        shareHint: 'يمكن للمشاركين اختيار قطعهم الخاصة',
      },
      stepLabels: ['اختر النوع', 'اختر القطع', 'مراجعة'],
      back: 'رجوع',
    },
    season: {
      eyebrow: 'هذا الموسم',
      headline: 'تشكيلة ٢٠٢٥',
      tabs: { all: 'الكل', tops: 'قمصان وبلوزات', trousers: 'بناطلون', dresses: 'فساتين وتنانير', outerwear: 'جاكيت', new: 'الجديد' },
      ctaBand: { eyebrow: 'ابدأ الآن', title: 'ابنِ صندوقك اليوم', cta: 'ابدأ الآن' },
      shopLink: 'أضف إلى الصندوق',
    },
    howItWorks: {
      eyebrow: 'كيف يعمل',
      headline: 'بسيط.\nشفاف.\nيستحق.',
      sub: 'أفضل مصانع مصر — من المصنع إلى بابك مباشرة.',
      steps: [
        { n: '01', title: 'اختر نوع صندوقك', body: 'كبسول ٥ قطع لنفسك، أو صندوق مجموعة ١٠ قطع تبنيه مع الأصدقاء والعائلة للحصول على خصم جماعي.', tip: 'الصندوق الجماعي يوفّر أكثر كلما اكتمل' },
        { n: '02', title: 'اختر قطعك', body: 'تصفّح المجموعة الموسمية وأضف ما يناسبك — كل قطعة مختارة يدوياً من مصانع التصدير المصرية المعتمدة.', tip: 'فقط جودة التصدير، بسعر المصنع' },
        { n: '03', title: 'شارك ووفّر ويصل', body: 'شارك الرابط مع الأصدقاء، اكتمل الصندوق واحصل على خصمك، ثم انتظر توصيله مباشرة إلى بابك.', tip: 'توصيل مجاني لكل الطلبات' },
      ],
      comparison: {
        capsule: { tag: 'فردي', name: 'صندوق الكبسول', points: ['٥ قطع مختارة يدوياً', 'توصيل فوري', 'إرجاع مجاني', 'جودة تصدير مضمونة'], cta: 'ابنِ كبسولك' },
        group: { tag: 'للمجموعة', name: 'صندوق المجموعة', points: ['١٠ قطع للمجموعة', 'خصم جماعي', 'رابط مشاركة', 'كل عضو يختار بنفسه'], cta: 'ابدأ مجموعتك' },
      },
      faq: [
        { q: 'ما الفرق بين صندوق الكبسول وصندوق المجموعة؟', a: 'صندوق الكبسول فردي من ٥ قطع تختارها لنفسك. صندوق المجموعة من ١٠ قطع يبنيه عدة أصدقاء معاً للحصول على خصم جماعي.' },
        { q: 'من أين تأتي الملابس؟', a: 'من أفضل مصانع التصدير المصرية المعتمدة — نفس المصانع التي تنتج للعلامات العالمية. نحن نحوّل الفائض إلى فرصة لك.' },
        { q: 'ما سياسة الإرجاع؟', a: 'إرجاع مجاني خلال ١٤ يوماً من الاستلام. فقط أعد الغلاف الأصلي وسنتولى الباقي.' },
        { q: 'كم يستغرق التوصيل؟', a: '٢–٣ أيام عمل داخل القاهرة والجيزة، و٣–٥ أيام لباقي المحافظات.' },
      ],
    },
    about: {
      eyebrow: 'عن قوم',
      headline: 'نلبّس مصر\nبقيمتها الحقيقية',
      manifesto: {
        title: 'قصتنا',
        paragraphs: [
          'أفضل مصانع مصر تُنتج للعلامات التجارية العالمية الكبرى — زارا، ماسيمو دوتي، H&M. لكن جزءاً من هذا الإنتاج يتبقى دون مستقرّ: فائض تصدير، قطع فائقة الجودة لا تحمل وجهة.',
          'قوم وُلِد من سؤال بسيط: لماذا لا يرتديها المصريون أولاً؟',
          'نحن لسنا بائع تصفية. نحن جسر مباشر بين المصنع وخزانتك — بشفافية كاملة في التسعير، وجودة لا تُساوم عليها.',
        ],
      },
      stats: [
        { n: '+٢٠', label: 'مصنع معتمد' },
        { n: '١٠٠٪', label: 'جودة تصدير' },
        { n: '٠', label: 'وسطاء' },
      ],
      pillars: [
        { icon: '◎', title: 'صفر هدر', body: 'نُحوّل فائض الإنتاج إلى فرصة حقيقية بدلاً من مكبّ النفايات. استدامة بالضرورة، ليس بالشعار.' },
        { icon: '◈', title: 'صُنع في مصر', body: 'نفس الخيوط والأيدي الماهرة التي تلبّس العالم — الآن تلبّسك أنت، بدون علاوة العلامة التجارية.' },
        { icon: '◉', title: 'شفافية التسعير', body: 'نُظهر لك التكلفة الفعلية والهامش الذي نأخذه. لا أسرار، لا سعر مبالغ فيه.' },
      ],
      cta: { eyebrow: 'انضم إلينا', title: 'ابنِ صندوقك اليوم', button: 'ابدأ الآن' },
    },
    review: {
      eyebrow: 'مراجعة طلبك',
      title: 'صندوقك',
      emptySlot: 'فارغ',
      editLink: 'تعديل الاختيار',
      pricing: [
        { label: 'سعر المصنع المباشر', value: 'توفير ٤٠٪' },
        { label: 'جودة تصدير مضمونة', value: '١٠٠٪' },
        { label: 'وسطاء', value: 'صفر' },
      ],
      summary: {
        title: 'ملخص الطلب',
        capsule: 'صندوق الكبسول — ٥ قطع',
        group: 'صندوق المجموعة — ١٠ قطع',
        subtotal: 'إجمالي القطع',
        shipping: 'شحن',
        shippingFree: 'مجاناً',
        total: 'الإجمالي',
        capsulePrice: '١٩٤٪ ج.م',
        groupPrice: '٢٦٣٩٪ ج.م',
        groupDiscount: 'خصم المجموعة',
        groupDiscountVal: '١٥٪',
      },
      form: {
        name: 'الاسم الكامل',
        phone: 'رقم الهاتف',
        address: 'عنوان التوصيل',
        confirm: 'تأكيد الطلب',
        hint: 'الدفع عند الاستلام — لا تتطلب هذه الخطوة بطاقة بنكية',
      },
    },
    invite: {
      eyebrow: 'صندوق المجموعة',
      invitedBy: 'دعاك',
      inviteText: 'إلى صندوق مجموعته',
      discountTitle: 'خصم المجموعة الحالي',
      progress: 'من ١٠ قطع',
      membersTitle: 'الأعضاء',
      statusDone: 'تم',
      statusPicking: 'يختار...',
      yourSlot: 'مكانك',
      pending: 'في انتظارك',
      cta: 'انضم واختر قطعك',
    },
    preorder: {
      eyebrow: 'PRE-ORDER',
      title: 'طلب مسبق',
      sub: 'احجز مكانك في التشكيلة القادمة',
      empty: 'لا توجد منتجات متاحة للطلب المسبق حالياً',
      openBadge: 'مفتوح',
      fundedBadge: 'مُموَّل',
      expiredBadge: 'انتهى',
      orderedLabel: 'محجوز',
      targetLabel: 'هدف',
      deadlineLabel: 'ينتهي',
      commitCta: 'احجز الآن',
      modal: {
        sizeLabel: 'المقاس',
        colorLabel: 'اللون',
        nameLabel: 'الاسم',
        phoneLabel: 'رقم الهاتف',
        addressLabel: 'عنوان التوصيل',
        paymentNote: 'الدفع عند الاستلام — لا تتطلب هذه الخطوة بطاقة بنكية',
        confirmCta: 'تأكيد الحجز',
        cancelCta: 'إلغاء',
      },
    },
  },
  en: {
    nav: {
      logo: 'QOM',
      items: [
        { label: 'Build a Box', href: '/build' },
        { label: 'Pre-Order', href: '/preorder' },
        { label: 'How It Works', href: '/how-it-works' },
        { label: 'This Season', href: '/season' },
        { label: 'About', href: '/about' },
      ],
      langSwitch: 'ع',
      cta: 'Build Your Box',
    },
    hero: {
      eyebrow: 'EXPORT · FACTORY · EGYPT',
      headline: 'Export Quality.\nFactory Price.',
      sub: "Egypt's best factories dress the world.\nNow they dress you.",
      learnMore: 'Learn more',
    },
    grid: {
      label1: 'Egyptian Linen — Season 2025',
      label2: "Men's Collection",
      label3: 'The Essentials',
      label4: 'Linen Edit',
      label5: 'Featured Looks',
    },
    boxes: {
      eyebrow: 'THIS SEASON',
      title: 'Thoughtfully Curated Boxes',
      sub: 'Every piece hand-picked from certified Egyptian export factories',
      capsule: {
        tag: 'Individual',
        name: 'Capsule Box',
        pieces: '5 hand-picked pieces',
        desc: "Your essential wardrobe kit for the season — 5 coordinated pieces from Egypt's finest factories, delivered to your door.",
      },
      group: {
        tag: 'For Groups',
        name: 'Group Box',
        pieces: '10 shared pieces',
        desc: 'Share the link with friends and family, build the box together — the more who join, the deeper the discount for everyone.',
      },
    },
    how: {
      title: 'How It Works',
      steps: [
        { n: '01', title: 'Choose Your Box', desc: 'A 5-piece Capsule for yourself, or a 10-piece Group Box to build together with friends and family.' },
        { n: '02', title: 'Pick Your Pieces', desc: 'Browse the collection and select what you love — at the factory price, direct, no middleman.' },
        { n: '03', title: 'Share & Save', desc: 'Share your link with friends. The fuller the group box, the deeper the discount for everyone.' },
      ],
    },
    sustain: {
      eyebrow: 'WHY QOM',
      title: 'More Than Just Clothes',
      pillars: [
        { icon: '◎', title: 'Zero Surplus', desc: 'We turn export overruns into real opportunity — not landfill' },
        { icon: '◈', title: 'Made in Egypt', desc: 'The same factories that dress global brands — now yours, direct' },
        { icon: '◉', title: 'Together We Save', desc: 'Our group box model makes export-quality fashion accessible to everyone' },
      ],
    },
    footer: {
      desc: 'Export-quality clothing, direct from Egyptian factories to your door.',
      col1title: 'QOM',
      col1: ['About', 'Transparency', 'Our Factories', 'Journal'],
      col2title: 'Help',
      col2: ['Contact Us', 'Shipping', 'Returns', 'FAQ'],
      tagline: 'Made in Egypt. Designed for the World.',
      copy: '© 2025 QOM — All rights reserved',
    },
    builder: {
      step1: {
        eyebrow: 'START HERE',
        title: 'Choose Your Box',
        sub: 'The Capsule Box is your individual pick, or go Group Box to save more with friends and family.',
        selectLabel: 'Select this box',
        capsule: { tag: 'Individual', name: 'Capsule Box', pieces: '5 pieces', desc: "Your essential wardrobe kit for the season. 5 hand-picked pieces from Egypt's finest export factories.", perks: ['5 pieces', 'Instant delivery', 'Free returns'] },
        group: { tag: 'For Groups', name: 'Group Box', discount: 'Group Discount', pieces: '10 pieces', desc: 'Share the link with friends — the more who join, the bigger the discount for every member.', perks: ['10 pieces', 'Share link', 'Group savings'] },
      },
      step2: {
        eyebrow: 'PICK YOUR PIECES',
        tabs: { all: 'All', tops: 'Tops & Shirts', trousers: 'Trousers', dresses: 'Dresses & Skirts', outerwear: 'Outerwear' },
        selectedLabel: 'selected',
        back: 'Back',
        reviewBox: 'Review Box',
      },
      step3: {
        eyebrow: 'REVIEW YOUR BOX',
        title: 'Your Box is Ready',
        emptySlot: 'empty',
        editBox: 'Edit selection',
        confirm: 'Confirm Order',
        shareEyebrow: 'INVITE FRIENDS',
        shareTitle: 'Share & Save Together',
        shareDesc: 'Share this link with friends. The more who join, the bigger the discount for everyone automatically.',
        shareHint: 'Each member picks their own pieces',
      },
      stepLabels: ['Choose Type', 'Pick Pieces', 'Review'],
      back: 'Back',
    },
    season: {
      eyebrow: 'THIS SEASON',
      headline: 'Collection 2025',
      tabs: { all: 'All', tops: 'Tops & Shirts', trousers: 'Trousers', dresses: 'Dresses & Skirts', outerwear: 'Outerwear', new: 'New' },
      ctaBand: { eyebrow: 'GET STARTED', title: 'Build Your Box Today', cta: 'Start Now' },
      shopLink: 'Add to Box',
    },
    howItWorks: {
      eyebrow: 'HOW IT WORKS',
      headline: 'Simple.\nTransparent.\nWorth it.',
      sub: "Egypt's best factories — direct from source to your door.",
      steps: [
        { n: '01', title: 'Choose Your Box Type', body: 'A 5-piece Capsule for yourself, or a 10-piece Group Box built together with friends and family for a group discount.', tip: 'Group Box saves more the fuller it gets' },
        { n: '02', title: 'Pick Your Pieces', body: 'Browse the seasonal collection and select what you love — every piece hand-picked from certified Egyptian export factories.', tip: 'Export quality only, at factory price' },
        { n: '03', title: 'Share, Save & Receive', body: 'Share the link with friends, complete the box for your discount, then wait for delivery directly to your door.', tip: 'Free shipping on all orders' },
      ],
      comparison: {
        capsule: { tag: 'Individual', name: 'Capsule Box', points: ['5 hand-picked pieces', 'Instant delivery', 'Free returns', 'Guaranteed export quality'], cta: 'Build Your Capsule' },
        group: { tag: 'For Groups', name: 'Group Box', points: ['10 pieces for the group', 'Group discount', 'Share link', 'Each member picks their own'], cta: 'Start Your Group' },
      },
      faq: [
        { q: "What's the difference between Capsule and Group Box?", a: "The Capsule Box is individual — 5 pieces you pick for yourself. The Group Box is 10 pieces built by multiple friends together to unlock a group discount." },
        { q: 'Where do the clothes come from?', a: "From Egypt's best certified export factories — the same ones that produce for global brands. We turn their surplus into an opportunity for you." },
        { q: "What's the return policy?", a: 'Free returns within 14 days of delivery. Just keep the original packaging and we handle the rest.' },
        { q: 'How long does delivery take?', a: '2–3 business days in Cairo and Giza, 3–5 days for other governorates.' },
      ],
    },
    about: {
      eyebrow: 'ABOUT QOM',
      headline: "Dressing Egypt\nat Its True Worth",
      manifesto: {
        title: 'Our Story',
        paragraphs: [
          "Egypt's best factories produce for the world's biggest brands — Zara, Massimo Dutti, H&M. But some of that production has no home: export surplus, flawless quality with nowhere to go.",
          "QOM was born from a simple question: why shouldn't Egyptians wear it first?",
          "We're not a clearance seller. We're a direct bridge between factory and wardrobe — full pricing transparency, uncompromising quality.",
        ],
      },
      stats: [
        { n: '+20', label: 'Certified Factories' },
        { n: '100%', label: 'Export Quality' },
        { n: '0', label: 'Middlemen' },
      ],
      pillars: [
        { icon: '◎', title: 'Zero Surplus', body: 'We turn production overruns into real opportunity instead of landfill. Sustainability by necessity, not by slogan.' },
        { icon: '◈', title: 'Made in Egypt', body: 'The same threads and skilled hands that dress the world — now dressing you, without the brand markup.' },
        { icon: '◉', title: 'Pricing Transparency', body: 'We show you the actual cost and the margin we take. No secrets, no inflated prices.' },
      ],
      cta: { eyebrow: 'JOIN US', title: 'Build Your Box Today', button: 'Get Started' },
    },
    review: {
      eyebrow: 'REVIEW YOUR ORDER',
      title: 'Your Box',
      emptySlot: 'empty',
      editLink: 'Edit selection',
      pricing: [
        { label: 'Direct Factory Price', value: 'Save 40%' },
        { label: 'Guaranteed Export Quality', value: '100%' },
        { label: 'Middlemen', value: 'Zero' },
      ],
      summary: {
        title: 'Order Summary',
        capsule: 'Capsule Box — 5 pieces',
        group: 'Group Box — 10 pieces',
        subtotal: 'Pieces Subtotal',
        shipping: 'Shipping',
        shippingFree: 'Free',
        total: 'Total',
        capsulePrice: 'EGP 1,299',
        groupPrice: 'EGP 2,399',
        groupDiscount: 'Group Discount',
        groupDiscountVal: '15%',
      },
      form: {
        name: 'Full Name',
        phone: 'Phone Number',
        address: 'Delivery Address',
        confirm: 'Confirm Order',
        hint: 'Cash on delivery — no credit card required at this step',
      },
    },
    invite: {
      eyebrow: 'GROUP BOX',
      invitedBy: 'invited you',
      inviteText: 'to their group box',
      discountTitle: 'Current Group Discount',
      progress: 'of 10 pieces',
      membersTitle: 'Members',
      statusDone: 'Done',
      statusPicking: 'Picking...',
      yourSlot: 'Your slot',
      pending: 'Pending',
      cta: 'Join & Pick Your Pieces',
    },
    preorder: {
      eyebrow: 'PRE-ORDER',
      title: 'Pre-Order',
      sub: 'Reserve your place in the next collection',
      empty: 'No pre-order products available right now',
      openBadge: 'Open',
      fundedBadge: 'Funded',
      expiredBadge: 'Closed',
      orderedLabel: 'Reserved',
      targetLabel: 'target',
      deadlineLabel: 'Closes',
      commitCta: 'Reserve Now',
      modal: {
        sizeLabel: 'Size',
        colorLabel: 'Colour',
        nameLabel: 'Full Name',
        phoneLabel: 'Phone Number',
        addressLabel: 'Delivery Address',
        paymentNote: 'Cash on delivery — no credit card required at this step',
        confirmCta: 'Confirm Reservation',
        cancelCta: 'Cancel',
      },
    },
  },
};
